# Generated by Django 4.2.6 on 2024-03-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
