# Generated by Django 4.2.6 on 2024-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_receipt_days_stayed_receipt_deducted_receipt_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='compiled',
            field=models.IntegerField(default=False, verbose_name='Compiled'),
        ),
    ]
