# Generated by Django 4.2.6 on 2024-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_receipt_compiled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='compiled',
            field=models.BooleanField(default=False, verbose_name='Compiled'),
        ),
    ]
