# Generated by Django 4.2.6 on 2024-01-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_language_alter_driver_truck_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Driver Id Number'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'عربي'), ('en', 'انجليزية'), ('ur', 'اوردو')], max_length=120, null=True, verbose_name='Driver Language'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Driver Name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=120, verbose_name='Driver Phone'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck_type',
            field=models.CharField(blank=True, choices=[('تريلة سطحة', 'تريلة سطحة'), ('تريلة ستارة', 'تريلة ستارة'), ('تريلة جوانب', 'تريلة جوانب'), ('تريلة براد', 'تريلة براد'), ('لوري عايدي', 'لوري عايدي'), ('لوري براد', 'لوري براد'), ('دينه عايدي', 'دينه عايدي'), ('دينة براد', 'دينة براد')], max_length=120, null=True, verbose_name='Truck Type'),
        ),
    ]
