# Generated by Django 4.2.6 on 2024-04-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='image_id',
            field=models.ImageField(blank=True, default='driver_image/id_defult.png', null=True, upload_to='driver_image', verbose_name='Driver Image'),
        ),
    ]
