# Generated by Django 4.2.6 on 2023-10-08 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_language_alter_driver_truck_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_remove_branch_address'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_company', to='customers.customers'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_driver', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
