# Generated by Django 4.2.6 on 2023-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipments_customer_alter_shipments_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='expected_arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
