# Generated by Django 4.2.6 on 2024-01-20 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_shipments_destination_alter_shipments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery Date '),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create At'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='days_stayed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days Stayed '),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='deducted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deducted'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='destination',
            field=models.CharField(choices=[('Jeddah', 'Jeddah'), ('Riyad', 'Riyad'), ('Dammam', 'Dammam')], max_length=20, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='expected_arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Arrival Date'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='fare',
            field=models.IntegerField(verbose_name='Fare'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Feedback', 'Feedback'), ('Late', 'Late'), ('Completed', 'Completed')], default='Recieved', max_length=20, verbose_name='Status '),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='stay_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stay Cost'),
        ),
    ]
