# Generated by Django 5.0 on 2024-01-23 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipments_actual_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='code',
            field=models.ImageField(blank=True, null=True, upload_to='code'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Actual Delivery Date '),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='expected_arrival_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Expected Arrival Date'),
        ),
    ]
