# Generated by Django 5.0 on 2024-01-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='code',
        ),
    ]
