# Generated by Django 5.0 on 2024-02-13 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_branch_city_alter_branch_name'),
        ('drivers', '0003_alter_driver_id_number_alter_driver_language_and_more'),
        ('shipments', '0009_delete_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipments',
            new_name='Shipment',
        ),
    ]
