# Generated by Django 5.0 on 2024-03-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_shipment_notes_shipment_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='City Arabic')),
                ('name_en', models.CharField(max_length=50, verbose_name='City English')),
            ],
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination',
        ),
    ]
