# Generated by Django 5.0 on 2024-03-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_shipment_destination_alter_shipment_days_stayed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='premium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Premium'),
        ),
    ]
