# Generated by Django 5.0 on 2024-03-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_alter_shipment_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50, verbose_name='City Arabic')),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.stages', verbose_name='Status'),
        ),
    ]
