# Generated by Django 4.2.6 on 2024-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0017_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.TextField(blank=True, choices=[('Recieved', 'Recieved'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Feedback', 'Feedback'), ('Late', 'Late'), ('Completed', 'Completed')], default='Recieved', null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status Stages'),
        ),
    ]
