# Generated by Django 4.2.6 on 2024-03-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0020_remove_shipment_status2_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
