# Generated by Django 4.2.6 on 2024-03-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0021_delete_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='fare_return',
            field=models.IntegerField(blank=True, null=True, verbose_name='Return'),
        ),
    ]
