# Generated by Django 4.2.6 on 2024-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0023_alter_shipment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='code',
            field=models.ImageField(blank=True, null=True, upload_to='code'),
        ),
    ]
