# Generated by Django 4.2.6 on 2024-03-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0024_alter_shipment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='return_fare',
            field=models.IntegerField(default=0, verbose_name='Return Fare'),
            preserve_default=False,
        ),
    ]
