# Generated by Django 4.2.6 on 2024-03-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0026_alter_shipment_return_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='return_fare',
        ),
    ]
