# Generated by Django 4.2.6 on 2024-04-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0027_remove_shipment_return_fare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
