# Generated by Django 4.2.6 on 2024-04-24 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0028_rename_create_at_shipment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Create At'),
        ),
    ]
