# Generated by Django 4.2.6 on 2023-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('id_number', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, choices=[('تريلة سطحة', 'تريلة سطحة'), ('تريلة ستارة', 'تريلة ستارة'), ('تريلة جوانب', 'تريلة جوانب'), ('تريلة براد', 'تريلة براد'), ('لوري عايدي', 'لوري عايدي'), ('لوري براد', 'لوري براد'), ('دينه عايدي', 'دينه عايدي'), ('دينة براد', 'دينة براد')], max_length=120, null=True)),
                ('truck_type', models.CharField(blank=True, choices=[('ar', 'عربي'), ('en', 'انجليزية'), ('ur', 'اوردو')], max_length=120, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
