# Generated by Django 4.2.6 on 2023-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'عربي'), ('en', 'انجليزية'), ('ur', 'اوردو')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck_type',
            field=models.CharField(blank=True, choices=[('تريلة سطحة', 'تريلة سطحة'), ('تريلة ستارة', 'تريلة ستارة'), ('تريلة جوانب', 'تريلة جوانب'), ('تريلة براد', 'تريلة براد'), ('لوري عايدي', 'لوري عايدي'), ('لوري براد', 'لوري براد'), ('دينه عايدي', 'دينه عايدي'), ('دينة براد', 'دينة براد')], max_length=120, null=True),
        ),
    ]
