# Generated by Django 4.2.6 on 2024-03-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_id_number_alter_driver_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image_id',
            field=models.ImageField(blank=True, null=True, upload_to='driver_image', verbose_name='Driver Image'),
        ),
    ]
