# Generated by Django 4.2.6 on 2023-10-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_customers', to='customers.customers'),
        ),
    ]
