# Generated by Django 4.2.6 on 2024-01-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('logo', models.ImageField(upload_to='company', verbose_name='Company Logo')),
                ('subtitle', models.TextField(max_length=500, verbose_name='Subtitle')),
                ('facebool_link', models.URLField(blank=True, null=True, verbose_name='Facebool_link')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Twitter_link')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Youtube_link')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Company Phone')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Company Email')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Company Address')),
                ('android_app', models.URLField(blank=True, null=True, verbose_name='Android app')),
                ('ios_app', models.URLField(blank=True, null=True, verbose_name='ios app')),
                ('call_us', models.IntegerField(blank=True, null=True, verbose_name='call us')),
                ('email_us', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email us')),
            ],
        ),
    ]
