# Generated by Django 5.0 on 2024-01-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='company', verbose_name='Company Cover'),
        ),
    ]
