# Generated by Django 4.2.6 on 2023-10-08 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_alter_driver_language_alter_driver_truck_type'),
        ('customers', '0002_remove_branch_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('days_stayed', models.IntegerField(blank=True, null=True)),
                ('stay_cost', models.IntegerField(blank=True, null=True)),
                ('deducted', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('قيد المعالجة', 'قيد المعالجة'), ('قيد التحميل', 'قيد التحميل'), ('قيد التسليم', 'قيد التسليم'), ('قيد الرفع', 'قيد الرفع ')], default='قيد المعالجة', max_length=20)),
                ('destination', models.CharField(choices=[('جدة', 'جدة'), ('الرياض', 'الرياض'), ('الدمام', 'الدمام')], max_length=20)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_arrival_date', models.DateTimeField()),
                ('actual_delivery_date', models.DateTimeField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_company', to='customers.customers')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_driver', to='drivers.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
