# Generated by Django 4.2.6 on 2023-10-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_branch_address'),
        ('shipments', '0003_alter_shipments_actual_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipments',
            name='customer',
        ),
        migrations.AddField(
            model_name='shipments',
            name='customer_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_company', to='customers.branch'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='status',
            field=models.CharField(choices=[('قيد المعالجة', 'قيد المعالجة'), ('قيد التحميل', 'قيد التحميل'), ('قيد التسليم', 'قيد التسليم'), ('قيد الرفع', 'قيد الرفع ')], default='قيد التحميل', max_length=20),
        ),
    ]
