# Generated by Django 5.0 on 2024-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_shipments_code_alter_shipments_actual_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.ImageField(blank=True, null=True, upload_to='code')),
            ],
        ),
    ]
