# Generated by Django 5.0 on 2024-03-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_city_remove_shipment_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.city', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='days_stayed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days Stayed '),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='deducted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deducted'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='stay_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stay Cost'),
        ),
    ]
