# Generated by Django 5.0 on 2024-03-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_stages_alter_shipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stages',
            old_name='Status',
            new_name='status',
        ),
    ]
