# Generated by Django 4.2.6 on 2024-03-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0018_alter_shipment_status_alter_stages_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_status2', to='shipments.stages', verbose_name='Status2'),
        ),
    ]
