# Generated by Django 4.2.6 on 2024-03-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0022_shipment_fare_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='code',
            field=models.ImageField(blank=True, null=True, upload_to='shipment_code'),
        ),
    ]
