# Generated by Django 4.2.6 on 2024-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0028_rename_create_at_shipment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.TextField(blank=True, choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Late', 'Late'), ('Feedback', 'Feedback')], default='Shipped', null=True, verbose_name='Status'),
        ),
    ]
