# Generated by Django 4.2.6 on 2024-09-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0029_alter_shipment_status'),
        ('shipments', '0030_alter_shipment_created_at'),
    ]

    operations = [
    ]
