# Generated by Django 4.2.15 on 2024-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0032_shipmentstatus_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentstatus',
            options={},
        ),
    ]
