# Generated by Django 4.2.6 on 2024-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_alter_receipt_compiled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='fare',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fare'),
        ),
    ]
